### ISSUE TITLE
Templating engine needed

### ISSUE THREAD

**Issue by nicklathe** [howarddierking/building-restful-services#13]
As I think about this project more, I think a templating engine will greatly ease the development of the client. I've used ejs before, but it requires node. However if we want to stick with a strictly browser-based client, something like mustache.js could do the trick. Any preference here?

**Comment by howarddierking** [comment]
I dig browser based over a second server. Mustache sounds like a good choice.

**Comment by howarddierking** [comment]
@nicklathe - still needed?

**Comment by nicklathe** [comment]
Nope. Not needed anymore.
