### ISSUE TITLE
build simple client to consume static resource model

### ISSUE THREAD

**Issue by howarddierking** [howarddierking/building-restful-services#4]

**Comment by howarddierking** [comment]
hey @nicklathe - if you think we'll run into a CORS issue here, I can serve the static site using Vagrant and NGINX rather than the python server. Part of me thinks that might be a good idea anyway just so that the viewer only needs Vagrant in order to get samples to work. The tradeoff is that setup in code will have more things (e.g. Vagrantfile, NGINX conf, etc.) 

thoughts?

**Comment by nicklathe** [comment]
I personally think that, if we can avoid delving into Vagrant/NGINX, we should. I worry that it may be distracting for the average developer trying to better understand REST. That's my initial reaction, but if you think that the kind of developer watching this course would be familiar enough with those technologies, then we can go for it.

**Comment by howarddierking** [comment]
I think that in order to demonstrate setting things like cache headers without having to write a server in something like nodejs, we'll need something basic like NGINX. I'll plan on deferring that work, though until I get to that part.

**Comment by howarddierking** [comment]
One thing I don't want to see lost on the client - it should start out by processing the vanilla JSON documents. This will give us the ability to see how more/less helpful each of the other types (and their associated client libraries) are.

**Comment by howarddierking** [comment]
working through the script now - how is the client progressing?

**Comment by howarddierking** [comment]
any reason for introducing bower? Just don't want to grow the complexity unnecessarily.

**Comment by nicklathe** [comment]
Bower was the only way to get the Hal JSON library, other than downloading a zip file from their docs site. Bower seemed cleaner out of the two options. Since I had to use it for that, I decided to use it for other dependencies. If we decide their is a better way, let's go for it!

**Comment by howarddierking** [comment]
yup - just discovered that as well. I'm merging hal into master currently - and I would like to leave the stuff in /json alone for the moment and possibly go back and use bower for those later.
